name: Build and Deploy Website
on:
  push:
    branches:
      - main

concurrency:
  group: 'deploy-website'
  cancel-in-progress: true

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 10_000

      - name: Get Node Version
        id: node-version
        run: |
          echo "node-version=$(cat .node-version)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Website
        env:
          NODE_ENV: production
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: website-build
          path: ./dist
          include-hidden-files: true
          retention-days: 3

  deploy:
    name: Deploy Website
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v6
        with:
          name: website-build
          path: ./dist

      - name: Deploy via FTP
        run: |
          printf "${{ secrets.FTP_PASSWORD }}" > .ftp-credentials
          chmod 600 .ftp-credentials

          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.FTP_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

          sshpass -f ./.ftp-credentials \
            rsync \
              -avzh --delete --checksum \
              ./dist/ \
              "${{ secrets.FTP_USER }}@${{ secrets.FTP_HOST }}:${{ secrets.FTP_ROOT_PATH }}"

          rm -f .ftp-credentials
